### ISSUE TITLE
The HTC Vive controllers do not appear in any Unity Scene

### ISSUE THREAD

**Issue by castana1962** [ValveSoftware/Moondust#1]
Hi. 
I am sorry for my ignorance but I am trying this Moondust project with the HTC Vive and its first Controllers( not Knuckles ones) in Unity and these controllers do not appear in any example, for it, Could anybody help me to fix it? Would it be possible?
Thanks for your time

**Comment by wirelessdreamer** [comment]
Not to sound rude, but the readme on the main page specifically states the demo only works with knuckles controllers, and not original vive controllers, I think your out of luck.

**Comment by castana1962** [comment]
Hi wirelessdreamer 
Pleasse do not worry, You are right, I made a mistake. Now I got thae EV3 and I will try this Moondust project.
Regards
