### ISSUE TITLE
Timeline for updating with the latest SteamVR input and DV3 support

### ISSUE THREAD

**Issue by SimonDarksideJ** [ValveSoftware/Moondust#2]
Are there any indications of timescales to update the Moondust demo with the latest SteamVR input beta and include DV support? (although I suspect the EV3 support would be sufficient for DV compatibility)

**Comment by keithbradner** [comment]
I'd say in the next weekish

**Comment by k0091601** [comment]
Still on its way?

**Comment by keithbradner** [comment]
Little later than we planned, still coming

**Comment by keithbradner** [comment]
Sorry this took a bit longer than expected. Released today so closing this issue.
