### ISSUE TITLE
Knuckles controllers for NASA simulations

### ISSUE THREAD

**Issue by JoshKlint** [ValveSoftware/Moondust#3]
Hi, I work for NASA at Goddard Space Flight Center. We are building a series of training simulations and public outreach projects (free VR games). My team is interested in working with Valve's new controller prototypes, as these will support improved dexterity for more realistic operations. Is there any way we can obtain a couple pairs of these?

**Comment by keithbradner** [comment]
Hi Josh, if you can send me an email at [removed] I can connect you to the right people.

**Comment by JoshKlint** [comment]
Thank you.
